# This is a basic workflow to help you get started with Actions

name: Test internal links

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
      - '!main'

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build: # This workflow contains a single job called "build"
    runs-on: ubuntu-latest # The type of runner that the job will run on
    env:
      BUNDLE_WITH: test jekyll_plugins
      SITE_ID:  'api' # which iiif site this is
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
    - name: Checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v6
    - name: Export BRANCH_NAME # store branch name in $BRANCH_NAME
      run: echo BRANCH_NAME=`git rev-parse --abbrev-ref HEAD` >> $GITHUB_ENV
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install
      run: gem install bundler && bundle
    - name: Build preview site
      run: bundle exec rake build:preview
    - name: Test html
      run: bundle exec rake test:html
    - name: Test internal links
      run: bundle exec rake test:links:internal
    - name: Test *iiif.io* links
      run: bundle exec rake test:links:iiif
    - name: Spec tests
      run: bundle exec rake api:spec
